# -*- coding: utf-8 -*-
"""Final four recipe enrichment entries."""

PART3 = {
    "one-pot-chicken-rice": {
        "story": {
            "en": [
                "One pot, one rhythm — that is how Gulf mothers teach daughters to cook chicken rice without fear of raw centers or scorched bottoms. Onion and spices bloom in oil first; rice absorbs the broth from seared chicken so every grain carries flavor, not just the pieces on top.",
                "Friday lunch often starts here when guests are few but expectations are high. Keep the lid on during the simmer — steam is doing half the work. Rest the pot five minutes off heat before fluffing so the rice sets instead of turning mush when you stir.",
            ],
            "ar": [
                "قدر واحد وإيقاع واحد — هكذا تعلّم الأمهات في الخليج رز الدجاج بلا خوف من وسط ناقص أو قاع محترق. البصل والبهارات تتفتح بالزيت أولاً؛ الأرز يشرب مرق الدجاج المحمّر فيصير كل حبة فيها نكهة.",
                "غداء الجمعة يبدأ هنا لما الضيوف قليل والتوقعات عالية. الغطاء مقفل وقت الغليان — البخار يسوي نصف الشغل. اتركي القدr خمس دقائق بعد النار قبل التفتيل عشان الأرز يتماسك.",
            ],
        },
        "successTips": {
            "en": [
                "Sear chicken skin-side down first even if you remove skin later — fond builds the broth.",
                "Rinse rice until water runs mostly clear; excess starch makes the pot gluey.",
                "Use a tight-fitting lid; foil under a loose lid traps steam in Gulf kitchens where lids warp.",
                "Do not stir once rice and liquid combine — stir only at the end when fluffing.",
                "Check doneness at the thickest chicken piece; rice timing follows chicken, not the reverse.",
            ],
            "ar": [
                "حمّري الدجاج جلد لتحت أول — حتى لو شلتِ الجلد، القاع يعطي مرق.",
                "اغسلي الأرز لين الماء يصير شبه صافي.",
                "غطاء محكم؛ ورق قصدير تحت الغطاء إذا ما يسكّر زين.",
                "لا تحرّكين بعد ما تدخل الأرز — تحريك آخر شي فقط.",
                "تأكدي من أسمك قطعة دجاج — الأرز يتبع الدجاج.",
            ],
        },
        "variations": {
            "en": [
                "Add 1/2 tsp ground cardamom with the rice for a lighter Gulf perfume.",
                "Stir in 1 cup frozen peas off heat for color and sweetness.",
                "Use basmati for long grains; Egyptian rice for stickier family-style pots.",
                "Swap water for low-sodium chicken stock for deeper flavor.",
            ],
            "ar": [
                "نصف ملعقة هيل مع الأرز — عبق خفيف.",
                "كوب بازيلا مجمدة بعد النار.",
                "بسمتي للحبات الطويلة؛ مصري للزيتني.",
                "مرق دجاج قليل الملح بدل الماء.",
            ],
        },
        "serving": {
            "en": "Fluff rice gently with a fork, not a spoon — spoons crush grains. Pile onto a wide platter with chicken pieces on top so guests see the meat first. Serve with yogurt-cucumber side and lemon wedges. Bring the pot to the table if serving family-style.",
            "ar": "فتّتي الأرز بالشوكة مو الملعقة. رتّبي في صينية واسعة والدجاج فوق. لبn وخيار ولمون جانباً.",
        },
        "storage": {
            "en": "Refrigerate up to 3 days in shallow containers for faster cooling. Reheat with splash of water in covered pan on low heat. Rice dries in microwave unless covered with damp towel.",
            "ar": "ثلاجة 3 أيام بعلب ضحلة. سخّني بماء قليل وغطاء على نار هادئة.",
        },
        "costNote": {
            "en": "About 6–9 SAR per serving (chicken, rice, onion, spices). Whole chicken cut at home beats pre-cut breast cost.",
            "ar": "حوالي 6–9 ريال للحصة. دجاج كامل وتقطيعه أوفر.",
        },
        "nutritionFull": {
            "calories": "455",
            "protein": "30 g",
            "carbs": "48 g",
            "fat": "16 g",
            "fiber": "2 g",
            "sodium": "490 mg",
        },
        "ingredients": {
            "en": [
                "800 g chicken pieces (thighs and drumsticks)",
                "2 cups (380 g) basmati rice, rinsed",
                "1 large onion, diced",
                "3 cups (720 ml) water or low-sodium chicken stock",
                "2 tbsp (30 ml) vegetable oil",
                "1 tsp ground cumin",
                "1/2 tsp ground turmeric",
                "1/2 tsp ground black pepper",
                "1 1/2 tsp fine salt",
                "2 tbsp chopped fresh parsley",
            ],
            "ar": [
                "800 غ قطع دجاج (أفخاذ وساق)",
                "كوبان (380 غ) أرز بسمتي مغسول",
                "بصلة كبيرة مفرومة",
                "3 أكواب (720 مل) ماء أو مرق دجاج",
                "ملعقتان كبيرتان زيت",
                "ملعقة صغيرة كمون",
                "نصف ملعقة كركم",
                "نصف ملعقة فلفل أسود",
                "ملعقة ونصف ملح",
                "ملعقتان كبيرتان بقدونس",
            ],
        },
        "steps": {
            "en": [
                "Season chicken with half the salt and pepper.",
                "Heat oil in a heavy pot; sear chicken 3–4 minutes per side. Remove to plate.",
                "Saute onion in same pot 5 minutes until soft.",
                "Add cumin and turmeric; stir 30 seconds.",
                "Return chicken; add rice, remaining salt, and stock.",
                "Bring to boil; reduce to low; cover tightly.",
                "Simmer 25–30 minutes without lifting lid.",
                "Rest off heat 5 minutes; fluff with fork and fold in parsley.",
            ],
            "ar": [
                "تبّلي الدجاج بنص الملح والفلفل.",
                "حمّري الدجاج 3–4 دقائق كل جهة؛ ارفعيه.",
                "البصل 5 دقائق.",
                "كمون وكركم 30 ثانية.",
                "ارجعي الدجاج؛ أرز وملح ومرق.",
                "اغلي ثم خفّفي وغطّي.",
                "25–30 دقيقة بلا فتح.",
                "راحة 5 دقائق؛ فتّتي وبقدونس.",
            ],
        },
    },
    "family-vegetable-stew": {
        "story": {
            "en": [
                "This stew is the quiet backbone of Gulf weeknight tables — potatoes and carrots in a gentle tomato broth that toddlers sip from spoons and adults season with lemon at the table. No aggressive spice; the vegetables themselves carry the meal.",
                "Zucchini goes in last so it holds shape instead of dissolving. The pot simmers uncovered toward the end if you want a thicker broth for bread dipping — Gulf families often tear khubz directly into the pot when nobody is watching formal manners.",
            ],
            "ar": [
                "هال يخنة العمود الفقري لعشاء أيام الأسبوع — بطاطس وجزر بمرق طماطم هادي العيal يشربونه بالملعقة والكبار يتبّlon باللمون. بلا بهارات عنيفة — الخضار هي الوجبة.",
                "الكوسا آخر شي عشان ما تذوب. القدr يغلي مكشوف آخر ربع ساعة إذا تبغين مرق أثخن للغمس بالخبز.",
            ],
        },
        "successTips": {
            "en": [
                "Cut potatoes and carrots similar size — carrots take longer if chunks are bigger than potatoes.",
                "Simmer on gentle bubble, not rolling boil; aggressive heat breaks vegetables apart.",
                "Add zucchini only in last 8 minutes; earlier addition turns it stringy.",
                "Taste broth before serving — tomato sweetness varies; adjust salt and lemon.",
                "A bay leaf in the pot adds depth; remove before serving so nobody bites it.",
            ],
            "ar": [
                "بطاطس وجزر بنفس الحجم.",
                "غليان هادئ — الغليان القوي يفتت الخضار.",
                "كوسا آخر 8 دقائق.",
                "ذوّقي المرق — حلاوة الطماطm تختلف.",
                "ورق غار للعمق — اشيليه قبل التقديم.",
            ],
        },
        "variations": {
            "en": [
                "Add 1 cup cooked chickpeas for protein without meat.",
                "Stir in 1 tsp dried mint off heat for a Levant-Gulf crossover note.",
                "Use sweet potato instead of regular for softer toddler texture.",
                "Blend half the pot for a creamy base while leaving chunks visible.",
            ],
            "ar": [
                "كوب حمص مطبوخ — بروتين بلا لحم.",
                "نعna مجفف بعد النار.",
                "بطاطا حلوة — أنعم للعيal.",
                "اطحني نص القدr واتركي قطع.",
            ],
        },
        "serving": {
            "en": "Ladle into deep bowls with broth covering vegetables. Offer lemon wedges and olive oil drizzle at the table. Warm bread on the side for dipping. Serve family-style from the pot for casual nights.",
            "ar": "اسكبي بمرq يغطي الخضار. لمون وزيت على الطاولة. خبز دافئ للغمس.",
        },
        "storage": {
            "en": "Refrigerate up to 4 days; flavors improve overnight. Reheat gently on stove. Freezes well up to 2 months — potatoes soften slightly on thaw but remain acceptable.",
            "ar": "ثلاجة 4 أيام — أطيب بكرة. تجميد شهرين؛ البطاطس تلين شوي.",
        },
        "costNote": {
            "en": "About 3–4 SAR per serving (potatoes, carrots, zucchini, tomato). One of the lowest-cost family dinners that feeds six.",
            "ar": "حوالي 3–4 ريال للحصة — من أرخص عشاء العائلة.",
        },
        "nutritionFull": {
            "calories": "225",
            "protein": "6 g",
            "carbs": "38 g",
            "fat": "6 g",
            "fiber": "7 g",
            "sodium": "420 mg",
        },
        "ingredients": {
            "en": [
                "3 medium potatoes (500 g), diced",
                "2 medium carrots (200 g), diced",
                "2 medium zucchini (300 g), diced",
                "1 medium onion, diced",
                "3 cloves garlic, minced",
                "2 tbsp (32 g) tomato paste",
                "6 cups (1.4 L) water or vegetable broth",
                "2 tbsp (30 ml) olive oil",
                "1 bay leaf",
                "1 1/2 tsp fine salt",
                "1/2 tsp black pepper",
            ],
            "ar": [
                "3 بطاطس (500 غ) مكعبات",
                "جزرتان (200 غ) مكعبات",
                "كوستان (300 غ) مكعبات",
                "بصلة متوسطة",
                "3 فصوص ثوم",
                "ملعقتان كبيرتان معجون طmاطm",
                "6 أكواب ماء أو مرq خضار",
                "ملعقتان زيت زيتون",
                "ورق غار",
                "ملعقة ونصف ملح",
                "نصف ملعقة فلفل",
            ],
        },
        "steps": {
            "en": [
                "Warm olive oil in a large pot over medium heat.",
                "Saute onion and garlic 4 minutes until softened.",
                "Stir tomato paste 1 minute; add potatoes, carrots, salt, pepper, bay leaf, and broth.",
                "Bring to boil; reduce to gentle simmer.",
                "Cook 20 minutes until potatoes and carrots are nearly tender.",
                "Add zucchini; simmer 8–10 minutes until all vegetables are soft.",
                "Adjust salt; remove bay leaf.",
                "Serve hot with lemon on the side.",
            ],
            "ar": [
                "زيت زيتون على نار متوسطة.",
                "بصل وثوم 4 دقائق.",
                "معجون دقيقة؛ بطاطس وجزر وملح وفلفl وغار ومرq.",
                "اغلي ثm خفّفي.",
                "20 دقيقة.",
                "كوسا 8–10 دقائق.",
                "ملح واشيلي الغار.",
                "قدّمي ساخنة مع لمون.",
            ],
        },
    },
    "grilled-chicken-salad": {
        "story": {
            "en": [
                "When summer evenings stay hot past eight, Gulf families want dinner without turning the kitchen into a sauna — grilled chicken on a bed of crisp greens fits that contract. The chicken carries smoke and char from a hot pan or grill; the salad stays cold and crunchy underneath.",
                "Marinate briefly in lemon and garlic so flavor penetrates without waiting hours. Slice chicken against the grain so each forkful with cucumber and lettuce feels tender, not stringy. This is a shared platter meal — one large bowl in the center, everyone builds their own plate.",
            ],
            "ar": [
                "لما أمسيات الصيف حارة بعد الثامنة، العائلة تبي عشاء بلا ما المطبخ يصير سauna — دجاج مشوي على خضار ورقية مقرمshة. الدجاج فيه نكهة الحrp والتحمير؛ السلطة باردة وقرmشة تحت.",
                "تتبيلة سريعة بلمون وثوم — نكهة بلا انتظار ساعات. قطّعي الدجاج عكس اتجاه الألياf عشان كل لقمة طرية. وجبة صينية مشتركة في الوسط.",
            ],
        },
        "successTips": {
            "en": [
                "Dry chicken well before grilling — moisture prevents browning.",
                "Rest cooked chicken 5 minutes before slicing; juices redistribute instead of flooding the salad.",
                "Dress greens lightly with lemon and oil just before serving — dressed salad wilts in Gulf heat.",
                "Use romaine or iceberg for crunch; soft butter lettuce collapses under warm chicken.",
                "Grill or sear over medium-high, not max heat — char without raw centers.",
            ],
            "ar": [
                "جفّفي الدجاج قبل الشوي.",
                "راحة 5 دقائق قبل التقطيع.",
                "تتبيلة خفيفة للخس وقت التقديم — يذbl تحت الحر.",
                "خس رومaine أو iceberg للقرmشة.",
                "نار متوسطة-عالية — تحمير بلا وسط ناقص.",
            ],
        },
        "variations": {
            "en": [
                "Add sumac and pomegranate seeds for color on special nights.",
                "Use boneless thighs instead of breast for juicier salad protein.",
                "Swap lemon dressing for tahini-lemon if you want a richer Gulf finish.",
                "Add toasted pita chips just before serving for crunch.",
            ],
            "ar": [
                "سماق ورمان — لليلة م special.",
                "أفخاذ بدون عظم — أjuicier.",
                "طحينة ولمون — نهاية أغنى.",
                "خبز محمّص مقطّع آخر شي.",
            ],
        },
        "serving": {
            "en": "Arrange greens on a large platter. Fan sliced chicken across the top. Scatter cucumber, tomato, and herbs. Drizzle dressing in thin lines, not pools. Serve immediately while chicken is warm against cold salad.",
            "ar": "خس في صينية كبيرة. دجاج مقطّع فوق. خيار وطماطm وأعشاب. صلصة بخطوط رفيعة. فوراً.",
        },
        "storage": {
            "en": "Store chicken and undressed salad separately up to 2 days. Assemble only when serving — dressed salad wilts within an hour. Reheat chicken gently or serve cold in wraps next day.",
            "ar": "دجاج وسلطة سادة منفصلين يومين. رتّبي وقت الأكل.",
        },
        "costNote": {
            "en": "About 7–10 SAR per serving (chicken breast, greens, cucumber, lemon). Buying whole chicken and using breast for salad, thighs for another meal stretches cost.",
            "ar": "حوالي 7–10 ريال للحصة.",
        },
        "nutritionFull": {
            "calories": "320",
            "protein": "28 g",
            "carbs": "12 g",
            "fat": "18 g",
            "fiber": "4 g",
            "sodium": "380 mg",
        },
        "ingredients": {
            "en": [
                "600 g chicken breast",
                "6 cups (200 g) romaine lettuce, chopped",
                "1 large cucumber (200 g), sliced",
                "2 medium tomatoes (250 g), wedged",
                "3 tbsp (45 ml) olive oil",
                "2 tbsp (30 ml) lemon juice",
                "2 cloves garlic, minced",
                "1 tsp fine salt",
                "1/2 tsp black pepper",
                "2 tbsp chopped fresh parsley",
            ],
            "ar": [
                "600 غ صدر دجاج",
                "6 أكواب (200 غ) خس رومaine",
                "خيار كبير (200 غ) شرائح",
                "حبتان طmاطm (250 غ)",
                "3 ملاعق كبيرة زيت زيتون",
                "ملعقتان كبيرتان عصير ليمون",
                "2 فصوص ثوم",
                "ملعقة صغيرة ملح",
                "نصف ملعقة فلفل",
                "ملعقتان كبيرتان بقدونس",
            ],
        },
        "steps": {
            "en": [
                "Marinate chicken with 1 tbsp oil, garlic, half the salt, and pepper 15 minutes.",
                "Grill or sear chicken 5–6 minutes per side until 74 C internal.",
                "Rest 5 minutes; slice against the grain.",
                "Whisk remaining oil, lemon, and remaining salt for dressing.",
                "Toss lettuce and cucumber with half the dressing.",
                "Arrange on platter; top with chicken and tomatoes.",
                "Drizzle remaining dressing and scatter parsley.",
                "Serve immediately.",
            ],
            "ar": [
                "تتبيلة 15 دقيقة.",
                "شوي 5–6 دقائق كل جهة.",
                "راحة وتقطيع.",
                "اخلطي صلصة.",
                "خس وخيار بنص الصلصة.",
                "رتّبي ودجاج وطماطm.",
                "باقي الصلصة وبقدونس.",
                "قدّمي فوراً.",
            ],
        },
    },
    "friday-family-pasta": {
        "story": {
            "en": [
                "Friday pasta is the compromise dish — kids get noodles, parents sneak vegetables through a blended tomato-carrot sauce that tastes sweeter than it looks healthy. Gulf families make it after Jumuah when nobody wants a heavy mandi but everyone expects something celebratory on the table.",
                "Blend cooked carrots into the sauce for body and natural sweetness without added sugar. Keep the texture slightly chunky so it reads as homemade, not baby food. A pot big enough for seconds is intentional — Friday leftovers become Saturday lunch.",
            ],
            "ar": [
                "معكرونة الجمعة وجبة الصلح — العيal ياكلون noodles والأهل يدخلون الخضار بصلصة طmاطm وجزر مهروسة أحلى مما تبان صحية. تتسوّى بعد الجمعة لما ما أحد يبي مندي ثقيل بس يتوقع شي على الطaولة.",
                "اطحني الجزر المطبوخ في الصلصة — قوام وحلاوة طبيعية بلا سكر. خليها قطع مو ناعمة زيada — كأنها بيتية. القدr الكبير مقصود — بقايا السبت غداء.",
            ],
        },
        "successTips": {
            "en": [
                "Roast or simmer carrots until very soft before blending — raw carrot grit never smooths out.",
                "Reserve pasta water; add to sauce until it coats noodles like thin cream.",
                "Undercook pasta by 1 minute before tossing with sauce — it finishes in the pan.",
                "Taste sauce before blending fully; adjust salt while it is still loose.",
                "Serve in the pot at the table for informal Friday energy — bowls optional.",
            ],
            "ar": [
                "جزر طري جداً قبل الهرس — الني ما ينعم.",
                "احتفظي بماء المعكرونة للتغليف.",
                "اسلقي المعكرونة أقل دقيقة — تكمل بالصلصة.",
                "ذوّقي قبل ما تهرسين كامل.",
                "قدّمي من القدr على الطaولة.",
            ],
        },
        "variations": {
            "en": [
                "Add 1/2 tsp ground cinnamon for a subtle Gulf sweet-savory note.",
                "Stir in 1 cup shredded chicken from leftover rotisserie.",
                "Use penne or fusilli — shapes that hold chunky sauce in crevices.",
                "Top with grated cheese only on adult portions if kids prefer plain.",
            ],
            "ar": [
                "نصف ملعقة قرفة — حلاوة خفيفة.",
                "كوب دجاج مفتت من باقi أمس.",
                "معكرونة قصيرة تمسك الصلصة.",
                "جبن للكبار على الطaولة.",
            ],
        },
        "serving": {
            "en": "Toss pasta and sauce in the pot until every piece is coated. Serve with extra black pepper and olive oil at the table for adults. A simple cucumber plate cools the meal. Eat while hot — this sauce tightens as it sits.",
            "ar": "قلّبي في القدr لين تتغطى كل قطعة. فلفl وزيت للكبار. خيار جانباً. كلوا وهي ساخنة.",
        },
        "storage": {
            "en": "Refrigerate up to 3 days. Reheat in pan with 3–4 tbsp water, stirring until saucy again. Freezes acceptably 1 month — sauce may separate slightly; stir well on reheat.",
            "ar": "ثلاجة 3 أيام. سخّني بماء. تجميد شهر — حرّكي زين.",
        },
        "costNote": {
            "en": "About 4–6 SAR per serving (pasta, carrots, tomato, onion). Feeds six from one pot — strong value for Friday gatherings.",
            "ar": "حوالي 4–6 ريال للحصة — قدر واحد يكفي ستة.",
        },
        "nutritionFull": {
            "calories": "385",
            "protein": "14 g",
            "carbs": "64 g",
            "fat": "9 g",
            "fiber": "6 g",
            "sodium": "410 mg",
        },
        "ingredients": {
            "en": [
                "500 g dry pasta (penne or fusilli)",
                "3 medium carrots (300 g), peeled and sliced",
                "1 medium onion, diced",
                "3 cloves garlic, minced",
                "2 tbsp (32 g) tomato paste",
                "1 can (400 g) crushed tomatoes",
                "2 tbsp (30 ml) olive oil",
                "1 tsp fine salt",
                "1/2 tsp black pepper",
                "1/4 tsp ground cinnamon (optional)",
            ],
            "ar": [
                "500 غ معكرونة قصيرة",
                "3 جزر (300 غ) مقطّع",
                "بصلة متوسطة",
                "3 فصوص ثوم",
                "ملعقتان كبيرتان معجون طmاطm",
                "علبة (400 غ) طmاطm مهروسة",
                "ملعقتان زيت زيتون",
                "ملعقة ملح",
                "نصف ملعقة فلفl",
                "ربع ملعقة قرفة (اختياري)",
            ],
        },
        "steps": {
            "en": [
                "Boil carrots in salted water 15 minutes until very soft; reserve 1 cup cooking water.",
                "Blend carrots with crushed tomatoes until mostly smooth.",
                "Cook pasta in well-salted water until 1 minute shy of al dente; drain, reserve 1 cup pasta water.",
                "Saute onion in olive oil 5 minutes; add garlic and tomato paste 1 minute.",
                "Pour in blended sauce; simmer 10 minutes, adding carrot water if thick.",
                "Toss pasta with sauce over low heat 2 minutes, adding pasta water to coat.",
                "Season with salt, pepper, and cinnamon if using.",
                "Serve immediately from the pot.",
            ],
            "ar": [
                "جزر 15 دقيقة؛ احتfظي بكوب ماء.",
                "اطحني الجزر مع الطmاطm.",
                "معكرونة أقل دقيقة؛ احتfظي بماء.",
                "بصل 5 دقائق؛ ثوم ومعجون.",
                "صلصة 10 دقائق.",
                "قلّبي المعكرونة 2 دقيقة.",
                "تتبيل.",
                "قدّmي من القدr.",
            ],
        },
    },
}
