# -*- coding: utf-8 -*-
"""Data module for recipe enrichment generator."""

ENRICHMENT = {
    "iron-oats-breakfast": {
        "story": {
            "en": [
                "On a cool Riyadh morning when the house is still quiet, this pot of oats fills the kitchen with cinnamon and softened dates. Gulf mothers reach for it when energy dips in the second trimester but heavy food feels wrong — warm, gentle, and slow enough to eat while checking messages or packing a school bag.",
                "The trick is treating oats like a small stew rather than instant porridge: enough liquid to stay creamy, dates added off the heat so they stay soft but not mushy, and walnuts kept in visible pieces for crunch. Pair a bowl with orange slices on the side — vitamin C helps your body use the iron from oats and nuts. Portions and sweeteners vary by pregnancy; check with your care team if you manage gestational diabetes or anemia dosing.",
            ],
            "ar": [
                "في صباح رياضي بارد والبيت لسه هادئ، هالقدر من الشوفان يعبّي المطبخ برائحة القرفة والتمر اللين. وجبة يميل لها البيت الخليجي لما الطاقة تنزل في الثلث الثاني والأكل الثقيل ما يرتاح له المعدة — دافئ، خفيف، ويُؤكل بهدوء وإنتِ تتابعين رسائل أو ترتّبين شنطة المدرسة.",
                "السر إنك تعاملين الشوفان مثل يخنة صغيرة مو هريسة سريعة: سائل كافي يخلي القوام كريمي، التمر يدخل بعد ما تنزلين القدر عن النار عشان يلين بلا ما يذوب، والجوز يبقى قطع واضحة للقرمشة. قدّميها مع شرائح برتقال — فيتامين سي يساعد جسمك يستفيد من الحديد. الحصص والتحلية تختلف حسب حالة الحمل؛ راجعي فريق الرعاية إذا عندك سكري حمل أو متابعة أنيميا.",
            ],
        },
        "successTips": {
            "en": [
                "Toast rolled oats dry for 2 minutes before adding milk — deeper nutty flavor without extra sugar.",
                "Soak firm dates in warm milk 5 minutes; they blend into the oats faster.",
                "Stir chia in after removing from heat so they swell without making the pot gluey.",
                "Use fortified plant milk only if the label lists calcium and B12; not all Gulf brands match.",
                "This supports general pregnancy nutrition — not medical advice. Confirm iron targets and portions with your clinician.",
            ],
            "ar": [
                "حمصي الشوفان ناشف دقيقتين قبل الحليب — نكهة أغنى بلا سكر زائد.",
                "انقعي التمر القاسي في حليب دافئ 5 دقائق؛ يندمج أسرع مع الشوفان.",
                "أضيفي الشيا بعد النار عشان تنتفخ بلا ما يثخن القدر.",
                "استخدمي حليب نباتي مدعّم — راجعي الملصق للكالسيوم وفيتامين ب12؛ مو كل العلامات في الخليج متساوية.",
                "الوصفة تدعم التغذية العامة في الحمل — مو نصيحة طبية. أكّدي أهداف الحديد والحصص مع طبيبك.",
            ],
        },
        "variations": {
            "en": [
                "Swap walnuts for roasted pumpkin seeds if tree nuts are avoided in your plan.",
                "Use half milk and half water for a lighter bowl on queasy mornings.",
                "Stir in 1 tbsp unsweetened cocoa for a chocolate-date version kids may share.",
                "Make overnight oats: combine cold milk, oats, and chia; refrigerate; warm gently next day.",
            ],
            "ar": [
                "بدّلي الجوز بلب قرع محمّص إذا كان خطة الرعاية تتجنّب المكسرات.",
                "نص حليب ونص ماء لوجبة أخف في الصباح إذا الغثيان قوي.",
                "ملعقة كاكاو غير محلّى لنسخة شوكولاتة وتمر يحبها الأطفال.",
                "شوفان ليلي: اخلطي بارد، برّديه، وسخّنيه برفق في الصباح.",
            ],
        },
        "serving": {
            "en": "Ladle into deep bowls while still steamy. Top each portion with a few extra walnut pieces and a light drizzle of honey only if your care team allows added sugars. Serve with fresh orange or mandarin wedges on a side plate — not mixed in — so the citrus stays bright. A small glass of water alongside helps digestion after a fiber-rich start.",
            "ar": "اسكبي في أطباق عميقة وهي دافئة. زيّني كل حصة بقطع جوز إضافية ورشة عسل خفيفة فقط إذا سمح فريق الرعاية. قدّمي برتقال أو يوسفي على طبق جانبي — مو مخلوط — عشان يبقى طعم الحمضيات واضح. كوب ماء صغير يساعد الهضم بعد الألياف.",
        },
        "storage": {
            "en": "Refrigerate in a sealed container up to 3 days. The oats thicken as chia absorbs liquid; loosen with a splash of milk when reheating on low heat, stirring often. Do not freeze — texture turns grainy. For meal prep, store toppings (nuts, dates) separately and add when serving.",
            "ar": "في الثلاجة بعلبة محكمة حتى 3 أيام. الشوفان يثخن مع الشيا؛ أضيفي حليب عند التسخين على نار هادئة مع تحريك. لا تجمّديه — القوام يصير حبيبي. للتحضير المسبق، احفظي الإضافات (جوز، تمر) لوحدها وضيفيها وقت التقديم.",
        },
        "costNote": {
            "en": "About 4–6 SAR per serving in Gulf supermarkets (rolled oats, local dates, milk, walnuts). Buying dates in bulk and oats in large bags drops cost toward 3 SAR.",
            "ar": "تقريباً 4–6 ريال للحصة في أسواق الخليج (شوفان، تمر محلي، حليب، جوز). شراء التمر والشوفان بكميات أكبر ينزل التكلفة نحو 3 ريال.",
        },
        "nutritionFull": {
            "calories": "420",
            "protein": "14 g",
            "carbs": "58 g",
            "fat": "16 g",
            "fiber": "9 g",
            "sodium": "95 mg",
        },
        "ingredients": {
            "en": [
                "1 cup (90 g) rolled oats",
                "2 cups (480 ml) low-fat milk or fortified oat milk",
                "4 pitted Ajwa or Sukkari dates, finely chopped",
                "2 tbsp (20 g) crushed walnuts",
                "1 tbsp (12 g) chia seeds",
                "1/2 tsp ground cinnamon",
                "1 tsp honey (optional)",
            ],
            "ar": [
                "كوب (90 غ) شوفان",
                "كوبان (480 مل) حليب قليل الدسم أو شوفان مدعّم",
                "4 حبات تمر عجوة أو سكري منزوعة النوى ومفرومة",
                "ملعقتان كبيرتان (20 غ) جوز مجروش",
                "ملعقة كبيرة (12 غ) بذور شيا",
                "نصف ملعقة صغيرة قرفة مطحونة",
                "ملعقة صغيرة عسل (اختياري)",
            ],
        },
        "steps": {
            "en": [
                "Measure oats, milk, and toppings. Chop dates and crush walnuts; set aside.",
                "Optional: toast oats in the dry pot 2 minutes over medium heat until fragrant.",
                "Pour in milk; bring to a gentle simmer, not a rolling boil.",
                "Stir in oats; cook 8–10 minutes, scraping the bottom, until creamy and thick enough to coat a spoon.",
                "Remove from heat. Fold in dates, walnuts, and chia; rest 2 minutes.",
                "Stir in cinnamon. Taste; add honey only if needed.",
                "Divide into two bowls. Serve warm with citrus on the side.",
            ],
            "ar": [
                "جهّزي الشوفان والحليب والإضافات. فرّمي التمر واجروشي الجوز.",
                "اختياري: حمصي الشوفان في القدر الجاف دقيقتين على نار متوسطة.",
                "صبّي الحليب واتركيه يغلي بهدوء مو غليان قوي.",
                "أضيفي الشوفان واطبخي 8–10 دقائق مع تحريك حتى يثخن ويصير كريمي.",
                "ارفعي عن النار. اخلطي التمر والجوز والشيا واتركيها دقيقتين.",
                "أضيفي القرفة. ذوّقي؛ عسل فقط إذا احتجتِ.",
                "قسّمي على طبقين. قدّمي دافئة مع حمضيات جانباً.",
            ],
        },
    },
    "lentil-spinach-soup": {
        "story": {
            "en": [
                "This soup is what Gulf kitchens simmer when someone needs warmth without heaviness — red lentils breaking down into a silky base, spinach folded in at the last minute so it stays bright green. The smell of cumin and garlic in olive oil is the signal that dinner will be ready before the adhan, and there is only one pot to wash.",
                "Lentils carry iron and steady protein; spinach adds folate — both reasons this bowl shows up in pregnancy meal plans across the region. Keep the heat gentle after adding greens so they wilt rather than turn bitter. If your clinician tracks sodium or iron supplements, treat portions as part of your overall plan, not a standalone prescription.",
            ],
            "ar": [
                "هالشوربة اللي تطبخها مطابخ الخليج لما يبغون دفء بلا ثقل — عدس أحمر يذوب قاعدة ناعمة، سبانخ تدخل آخر شي تبقى خضراء زاهية. ريحة الكمون والثوم بالزيت علامة إن العشاء يجهز قبل الأذان وقدر واحد بس للغسل.",
                "العدس فيه حديد وبروتين ثابت؛ السبانخ فيها حمض فوليك — عشان كذا تظهر في خطط وجبات الحامل. خفّفي النار بعد الخضار عشان تذبل مو تمرّ. إذا طبيبك يتابع الملح أو مكملات الحديد، اعتبري الحصة جزء من خطتك الكاملة مو وصفة طبية لوحدها.",
            ],
        },
        "successTips": {
            "en": [
                "Rinse red lentils until water runs almost clear — less foam and cleaner flavor.",
                "Bloom cumin in oil 45 seconds before adding onion; depth without extra salt.",
                "Add spinach in two batches off a simmer; stir until just wilted, then stop cooking.",
                "Blend one cup of the finished soup if you want a creamier body without cream.",
                "Supports general pregnancy nutrition — not medical advice. Confirm iron and folate goals with your care team.",
            ],
            "ar": [
                "اغسلي العدس الأحمر لين الماء يصير شبه صافي — رغوة أقل وطعم أنظف.",
                "حمّري الكمون بالزيت 45 ثانية قبل البصل — عمق بلا ملح زائد.",
                "أضيفي السبانخ على دفعتين وهي تغلي بهدوء؛ حرّكي لين تذبل وبس.",
                "اطحني كوب من الشوربة الجاهزة إذا تبغين قوام أنعم بلا كريمة.",
                "تدعم التغذية العامة في الحمل — مو نصيحة طبية. أكّدي أهداف الحديد والفولات مع طبيبك.",
            ],
        },
        "variations": {
            "en": [
                "Stir in 1 tbsp lemon juice at the table for brightness without curdling the pot.",
                "Swap half the spinach for chopped Swiss chard when available at the market.",
                "Add 1 diced potato with the lentils for a thicker, kid-friendly bowl.",
                "Finish with a spoon of plain yogurt per bowl for Gulf-style tang.",
            ],
            "ar": [
                "عصرة ليمون على الطاولة — نكهة منعشة بلا ما تخرب القدر.",
                "بدّلي نص السبانخ بسلق مقطّع إذا لقيتيه في السوق.",
                "بطاطس مكعبات مع العدس — شوربة أثخن يرتاح لها العيال.",
                "ملعقة لبن على كل طبق — حموضة على طريقة الخليج.",
            ],
        },
        "serving": {
            "en": "Ladle into deep bowls while hot. Drizzle a thin thread of olive oil on top and add lemon wedges on the side so each person seasons to taste. Pair with warm pita or small rice portion if the meal needs to stretch for teens. Serve immediately — spinach color fades on holding.",
            "ar": "اسكبي في أطباق عميقة وهي ساخنة. خط رفيع زيت زيتون فوق وقدّمي ليمون جانباً عشان كل واحد يتبّل على ذوقه. مع خبز عربي دافئ أو حصة أرز صغيرة إذا الوجبة للكبار والصغار. قدّمي فوراً — لون السبانخ يبهت إذا انتهى.",
        },
        "storage": {
            "en": "Refrigerate up to 4 days in a sealed container. Reheat gently on the stove with a splash of water; do not boil hard after reheating or spinach turns dull. Freezes acceptably up to 2 months — thaw overnight and reheat slowly. Store lemon separately.",
            "ar": "ثلاجة 4 أيام بعلبة محكمة. سخّني على النار بقليل ماء؛ لا تغلي بقوة بعد التسخين عشان السبانخ ما تبهت. التجميد ينفع شهرين — فكّي بالليل وسخّني برفق. احفظي الليمون لوحده.",
        },
        "costNote": {
            "en": "About 3–5 SAR per serving (red lentils, spinach, onion, olive oil). One of the most affordable iron-rich soups in Gulf home cooking.",
            "ar": "حوالي 3–5 ريال للحصة (عدس أحمر، سبانخ، بصل، زيت). من أرخص الشوربات الغنية بالحديد في البيت الخليجي.",
        },
        "nutritionFull": {
            "calories": "245",
            "protein": "15 g",
            "carbs": "32 g",
            "fat": "7 g",
            "fiber": "12 g",
            "sodium": "410 mg",
        },
        "ingredients": {
            "en": [
                "1 cup (200 g) red lentils, rinsed",
                "6 cups (1.4 L) water or low-sodium vegetable broth",
                "1 medium onion, diced",
                "3 cloves garlic, minced",
                "1 tsp ground cumin",
                "1/2 tsp ground turmeric",
                "200 g fresh spinach, chopped",
                "2 tbsp (30 ml) olive oil",
                "1 tsp fine salt, plus more to taste",
                "1/2 tsp black pepper",
            ],
            "ar": [
                "كوب (200 غ) عدس أحمر مغسول",
                "6 أكواب (1.4 ل) ماء أو مرق خضار قليل الملح",
                "بصلة متوسطة مفرومة",
                "3 فصوص ثوم مفروم",
                "ملعقة صغيرة كمون مطحون",
                "نصف ملعقة صغيرة كركم",
                "200 غ سبانخ طازجة مفرومة",
                "ملعقتان كبيرتان (30 مل) زيت زيتون",
                "ملعقة صغيرة ملح ناعم",
                "نصف ملعقة صغيرة فلفل أسود",
            ],
        },
        "steps": {
            "en": [
                "Rinse lentils until water runs mostly clear. Dice onion and mince garlic.",
                "Warm olive oil in a heavy pot over medium heat. Add cumin; stir 45 seconds until fragrant.",
                "Add onion and garlic; cook 5 minutes until softened and lightly golden.",
                "Stir in lentils, turmeric, salt, pepper, and broth. Bring to a boil, then reduce to a steady simmer.",
                "Cook 25–30 minutes, stirring occasionally, until lentils collapse and soup is thick.",
                "Fold in spinach in two batches; cook 2–3 minutes until wilted. Adjust salt.",
                "Serve hot with lemon on the side. Optional: blend 1 cup for a creamier texture.",
            ],
            "ar": [
                "اغسلي العدس. فرّمي البصل والثوم.",
                "سخّني زيت الزيتون. حمّري الكمون 45 ثانية.",
                "أضيفي البصل والثوم 5 دقائق لين يلين ويأخذ لون.",
                "اخلطي العدس والكركم والملح والفلفل والمرق. اغلي ثم خفّفي النار.",
                "25–30 دقيقة مع تحريك — العدس ينكسر والشوربة تثخن.",
                "سبانخ على دفعتين 2–3 دقائق لين تذبل. عدّلي الملح.",
                "قدّمي ساخنة مع ليمون. اختياري: اطحني كوب للقوام الأنعم.",
            ],
        },
    },
    "date-nut-smoothie": {
        "story": {
            "en": [
                "When appetite shrinks in late pregnancy but calories still matter, this blender drink lands like dessert — dates for natural sweetness, yogurt for protein, almond butter for staying power. Gulf families keep pitted dates in the freezer door and reach for them between clinic visits and school runs.",
                "The texture should pour thick but drinkable, not fork-thick like a pudding. Freeze the banana in coins if you want a colder glass without watering it down with ice. If gestational diabetes is part of your care plan, treat sweetness as something to confirm with your clinician — dates are whole food, but portions still count.",
            ],
            "ar": [
                "لما الشهية تضعف في آخر الحمل والسعرات لسه مهمة، هالمشروب من الخلاط يجي مثل حلى — تمر للتحلية الطبيعية، لبن للبروتين، زبدة لوز للشبع. أغلب بيوت الخليج تحفظ تمر منزوع النوى في المجمد وتمسكه بين المواعيد والمدرسة.",
                "القوام يكون ثخين يسيل بس مو زي مهلبية. جمدي الموز على شرائح إذا تبغين كاس بارد بلا ثلج يخفّف الطعم. إذا عندك سكري حمل، أكّدي الحلاوة والحصة مع طبيبك — التمر طبيعي بس الكمية لها حساب.",
            ],
        },
        "successTips": {
            "en": [
                "Soak firm dates in warm water 10 minutes before blending — smoother texture, less strain on the motor.",
                "Add liquid first, then soft items, then nut butter and ice last for even blending.",
                "Use full-fat plain yogurt for richness; strained laban works if that is what you keep at home.",
                "Blend 45 seconds, scrape sides, then 15 seconds more — stops grit from dates at the bottom.",
                "Calorie-dense snack for pregnancy — not medical advice. Confirm portions with your care team if appetite or blood sugar is monitored.",
            ],
            "ar": [
                "انقعي التمر القاسي في ماء دافئ 10 دقائق — أنعم في الخلاط وأخف على الموتور.",
                "السائل أول، بعدين اللين، بعدين زبدة اللوز والثلج آخر شي.",
                "لبن كامل الدسم أو لبن مصفى يعطي غنى — على حسب اللي في الثلاجة.",
                "45 ثانية خلط، كشطي الجوانب، 15 ثانية ثانية — يمنع بقايا تمر.",
                "وجبة خفيفة كثيفة السعرات للحمل — مو نصيحة طبية. أكّدي الحصة مع طبيبك إذا يتابع السكر أو الشهية.",
            ],
        },
        "variations": {
            "en": [
                "Swap almond butter for tahini for a more local pantry profile.",
                "Add 1 tbsp rolled oats for extra fiber and a slower energy release.",
                "Use frozen mango instead of banana when bananas run short at the souq.",
                "Thin with cold milk to serve in a cup with a straw for nausea-friendly sipping.",
            ],
            "ar": [
                "بدّلي زبدة اللوز بالطحينة — على ذوق المخزن الخليجي.",
                "ملعقة شوفان للألياف وطاقة أطول.",
                "مانجو مجمد بدل الموز إذا خلص من السوق.",
                "خفّفي بالحليب البارد وقدّمي بمصاصة — أنسب لو الغثيان.",
            ],
        },
        "serving": {
            "en": "Pour into chilled glasses immediately. Dust with a pinch of ground cinnamon if you like, and serve with a small plate of whole dates on the side for anyone who wants extra chew. Best consumed within minutes of blending before separation begins.",
            "ar": "صبّي في أكواب باردة فوراً. رشة قرفة اختيارية، وطبق تمر كامل جانباً لمن يبغي مضغ. أفضلها خلال دقائق من الخلط قبل ما تفصل الطبقات.",
        },
        "storage": {
            "en": "Drink fresh — separation and oxidation start within 30 minutes. If you must hold it, refrigerate up to 4 hours in a sealed bottle and shake hard before serving; texture will not match freshly blended.",
            "ar": "اشربيها طازجة — تفصل خلال نصف ساعة. إذا اضطررتِ، ثلاجة 4 ساعات بزجاجة محكمة ورجّي بقوة؛ القوام ما يكون مثل الطازج.",
        },
        "costNote": {
            "en": "About 5–7 SAR per serving (dates, yogurt, almond butter, banana). Bulk dates and store-brand yogurt keep it closer to 4 SAR.",
            "ar": "حوالي 5–7 ريال للحصة (تمر، لبن، زبدة لوز، موز). تمر بالجملة ولبن محلي ينزلها نحو 4 ريال.",
        },
        "nutritionFull": {
            "calories": "335",
            "protein": "14 g",
            "carbs": "42 g",
            "fat": "14 g",
            "fiber": "6 g",
            "sodium": "85 mg",
        },
        "ingredients": {
            "en": [
                "4 pitted Medjool or Sukkari dates",
                "1 cup (240 g) plain full-fat yogurt",
                "1 medium banana (about 120 g), fresh or frozen slices",
                "1 tbsp (16 g) almond butter",
                "1/2 cup (120 ml) cold milk or fortified oat milk",
                "1/4 tsp ground cinnamon",
                "4 ice cubes (optional)",
            ],
            "ar": [
                "4 حبات تمر مجلّج أو سكري منزوعة النوى",
                "كوب (240 غ) لبن طبيعي كامل الدسم",
                "موزة متوسطة (120 غ) طازجة أو مجمدة",
                "ملعقة كبيرة (16 غ) زبدة لوز",
                "نصف كوب (120 مل) حليب بارد",
                "ربع ملعقة صغيرة قرفة",
                "4 مكعبات ثلج (اختياري)",
            ],
        },
        "steps": {
            "en": [
                "If dates are firm, soak in warm water 10 minutes; drain.",
                "Add milk and yogurt to the blender first.",
                "Add dates, banana, almond butter, and cinnamon.",
                "Blend on medium-high 45 seconds until smooth.",
                "Scrape down sides; add ice if using.",
                "Blend 15–20 seconds more until pourable and thick.",
                "Taste; add 1 tbsp milk if too thick. Serve immediately.",
            ],
            "ar": [
                "انقعي التمر القاسي 10 دقائق وصفّيه.",
                "حليب ولبن في الخلاط أول.",
                "تمر، موز، زبدة لوز، قرفة.",
                "45 ثانية على سرعة متوسطة-عالية.",
                "كشطي الجوانب؛ ثلج إذا تبغين.",
                "15–20 ثانية إضافية لين يصير سائل ثخين.",
                "ذوّقي؛ حليب إذا ثخن زيادة. قدّمي فوراً.",
            ],
        },
    },
    "baked-salmon-veg": {
        "story": {
            "en": [
                "Sheet-pan dinners save Gulf weeknights when nobody wants another pot to scrub. Salmon, zucchini ribbons, and carrot coins roast on one tray — lemon slices tucked underneath so the fish stays moist and the kitchen smells like a quiet seaside lunch, not fried oil.",
                "Choose fillets of similar thickness so nothing overcooks while something else is still raw. Vegetables go in first because they need longer; salmon goes on top for the last stretch only. If your pregnancy care plan limits fish frequency or species, treat this as an occasional meal and confirm portions with your clinician — cooking method does not change medical guidance on mercury.",
            ],
            "ar": [
                "عشاء الصينية الواحدة ينقذ أمسيات الخليج لما ما أحد يبي يغسل قدر ثاني. سلمون وكوسا وجزر في صينية — شرائح ليمون تحت السمك عشان يبقى رطب والريحة مثل غداء بحر هادي.",
                "اختاري قطع بنفس السماكة عشان ما ينضج شي زيادة والثاني ناقص. الخضار أول لأنها تحتاج وقت؛ السلمون فوق في آخر مرحلة بس. إذا خطة الحمل تحدّ تكرار السمك، اعتبرها وجبة بين فترة وأخرى واسألي طبيبك — طريقة الطبخ ما تغيّر توجيه الزئبق.",
            ],
        },
        "successTips": {
            "en": [
                "Pat salmon dry before oiling — wet fish steams instead of roasting.",
                "Cut carrots thinner than zucchini; equal thickness cooks evenly on one tray.",
                "Insert salmon when vegetables are just starting to brown, not raw.",
                "Fish is done when center is opaque and flakes at the thickest part — use a thermometer if unsure (63 C internal).",
                "Not medical advice — follow your clinician guidance on fish type, frequency, and portion size during pregnancy.",
            ],
            "ar": [
                "جفّفي السلمون قبل الزيت — الرطب يتبخّر مو يتحمّص.",
                "الجزر أرفع من الكوسا — ينضجون مع بعض.",
                "دخّلي السلمون لما الخضار بدت تاخذ لون.",
                "ينضج لما الوسط متماسك وينفصل — 63 درجة تقريباً.",
                "مو نصيحة طبية — التزمي بتوجيه طبيبك لنوع السمك والكمية.",
            ],
        },
        "variations": {
            "en": [
                "Swap thyme for dried dill and add capers after baking for a different profile.",
                "Use thick-cut chicken breast strips if fish is off the menu this week.",
                "Add bell pepper wedges in season — they roast well beside zucchini.",
                "Line the tray with parchment for easier cleanup after late dinners.",
            ],
            "ar": [
                "شبت مجفف وكبر بعد الخبز — نكهة ثانية.",
                "شرائح دجاج سميكة بدل السمك.",
                "فلفل رومي موسمي بجانب الكوسا.",
                "ورق زبدة تحت — غسل أسهل.",
            ],
        },
        "serving": {
            "en": "Slide salmon and vegetables onto warm plates with the roasted lemon — squeeze over at the table. A small side of plain yogurt or a simple cucumber salad fits Gulf tables without adding heavy sauce. Serve immediately; fish texture suffers on a holding tray.",
            "ar": "انقلي السلمون والخضار لأطباق دافئة مع الليمون المحمّص — يعصر على الطاولة. لبن أو سلطة خيار جانباً. قدّمي فوراً.",
        },
        "storage": {
            "en": "Refrigerate leftovers up to 2 days in a sealed container. Reheat salmon gently in a covered pan over low heat or eat cold in a salad — microwave tends to dry fish. Vegetables reheat better than the fish; consider separating before storing.",
            "ar": "بقايا يومين بالثلاجة. سخّني السلمون على نار هادئة أو كسلطة باردة. افصلي السمك عن الخضار للتخزين.",
        },
        "costNote": {
            "en": "About 18–25 SAR per serving in Gulf cities (salmon fillet drives cost). Watch hypermarket promotions; frozen portioned fillets often beat fresh counter price.",
            "ar": "حوالي 18–25 ريال للحصة — السلمون هو الأغلى. عروض المجمد غالباً أوفر.",
        },
        "nutritionFull": {
            "calories": "410",
            "protein": "34 g",
            "carbs": "12 g",
            "fat": "26 g",
            "fiber": "4 g",
            "sodium": "380 mg",
        },
        "ingredients": {
            "en": [
                "4 salmon fillets (about 600 g total), similar thickness",
                "2 medium zucchini (400 g), sliced into half-moons",
                "2 medium carrots (200 g), thin coins",
                "2 lemons, sliced",
                "2 tbsp (30 ml) olive oil",
                "1 tsp dried thyme",
                "1 tsp fine salt",
                "1/2 tsp black pepper",
            ],
            "ar": [
                "4 قطع سلمون (600 غ تقريباً) بنفس السماكة",
                "كوسا متوسطتان (400 غ) شرائح",
                "جزرتان (200 غ) شرائح رفيعة",
                "ليمونتان شرائح",
                "ملعقتان كبيرتان زيت زيتون",
                "ملعقة صغيرة زعتر مجفف",
                "ملعقة صغيرة ملح",
                "نصف ملعقة صغيرة فلفل أسود",
            ],
        },
        "steps": {
            "en": [
                "Preheat oven to 200 C. Line a large baking tray.",
                "Toss zucchini and carrots with 1 tbsp oil, salt, pepper, and thyme.",
                "Roast vegetables 12 minutes until edges begin to color.",
                "Pat salmon dry; season both sides. Place on tray with lemon slices under fillets.",
                "Drizzle remaining oil over fish.",
                "Bake 10–12 minutes until salmon flakes and center is opaque.",
                "Rest 3 minutes; spoon pan juices over before serving.",
            ],
            "ar": [
                "سخّني الفرن 200 درجة. صينية بورق زبدة.",
                "اخلطي الكوسا والجزر بملعقة زيت وملح وفلفل وزعتر.",
                "12 دقيقة حتى تبدأ الحواف تاخذ لون.",
                "جفّفي السلمون؛ تتبيل. ضعيه مع ليمون تحته.",
                "رشّي باقي الزيت.",
                "10–12 دقيقة حتى ينفصل بسهولة.",
                "راحة 3 دقائق؛ صبّي العصير فوق.",
            ],
        },
    },
    "chickpea-rice-bowl": {
        "story": {
            "en": [
                "This bowl is what you build when the fridge has cooked rice from yesterday and a can of chickpeas in the pantry — a pattern every budget-conscious Gulf household knows after a big kabsa or mandi night. Turmeric stains the rice golden, tomatoes break down into a light sauce, and parsley at the end keeps it tasting fresh rather than reheated.",
                "It is not fancy, but it is honest: one pan, strong spice from cumin and turmeric, and enough fiber to keep a working parent full until dinner. Kids who resist plain rice often accept it once the chickpeas are lightly smashed and mixed through so every forkful has texture.",
            ],
            "ar": [
                "هالطبق يتسوّى لما يبقى أرز أمس وعلبة حمص في المخزن — عادة في كل بيت خليجي يحسب الميزانية بعد كبسة أو مندي. الكركم يصبّغ الأرز ذهبي، الطماطم تذوب صلصة خفيفة، والبقدونس آخر شي يعطي نكهة طازجة مو معاد تسخينه.",
                "مو فخم بس صادق: مقلاة واحدة، كمون وكركم، وألياف تشبع الموظف لين العشاء. العيال اللي ما يحبون أرز سادة غالباً يقبلونه لما تهرسين شوي الحمص ويوزّع بكل لقمة.",
            ],
        },
        "successTips": {
            "en": [
                "Use day-old rice refrigerated overnight — fresh hot rice turns mushy in the pan.",
                "Smash one-third of the chickpeas against the pan side to thicken the tomato layer.",
                "Bloom turmeric and cumin in oil 30 seconds before wet ingredients — sharper color, less bitterness.",
                "Finish with a squeeze of lemon off the heat; acid lifts canned chickpea flavor.",
                "If rice clumps, break with the back of a spoon and add 1 tbsp water to steam it loose.",
            ],
            "ar": [
                "أرز أمس من الثلاجة — الأرز الساخن الطازج يلين زيادة.",
                "اهرسي ثلث الحمص على جدار المقلاة — صلصة أثخن.",
                "حمّري الكركم والكمون بالزيت 30 ثانية قبل الطماطم.",
                "لمونة بعد النار — تفتح نكهة الحمص.",
                "أرز متكتل؟ اكسره بظهر الملعقة وملعقة ماء.",
            ],
        },
        "variations": {
            "en": [
                "Top with a fried egg per bowl for extra protein on training days.",
                "Stir in 1 tsp harissa paste for adult heat; leave kids portions plain.",
                "Swap parsley for fresh dill when you have it from a garden pot.",
                "Use brown rice for more fiber — add 2 tbsp water when reheating.",
            ],
            "ar": [
                "بيضة مقلية فوق كل طبق — بروتين زيادة.",
                "ملعقة هريسة حارة للكبار؛ حصص الأطفال سادة.",
                "شبت بدل بقدونس إذا متوفر.",
                "أرز بني — ملعقتان ماء وقت التسخين.",
            ],
        },
        "serving": {
            "en": "Pack into shallow bowls so the golden rice shows at the edges. Scatter parsley and a few whole chickpeas on top for contrast. Serve with lemon wedges and optional plain yogurt on the side — many families swirl yogurt through at the table. Eat warm the same day for best texture.",
            "ar": "أطباق ضحلة يبان فيها لون الأرز. بقدونس وحمص كامل فوق. لمون ولبن جانباً — كثير يخلطون اللبن على الطاولة. أفضلها دافئة اليوم نفسه.",
        },
        "storage": {
            "en": "Refrigerate up to 3 days in airtight containers. Microwave with a damp paper towel over the bowl, or reheat in a pan with a splash of water. Does not freeze well — rice texture becomes brittle.",
            "ar": "ثلاجة 3 أيام. ميكرويف بمنشفة رطبة أو مقلاة بقليل ماء. التجميد يخرب قوام الأرز.",
        },
        "costNote": {
            "en": "About 3–4 SAR per serving (rice, canned chickpeas, onion, tomato). One of the cheapest complete lunches in the library.",
            "ar": "حوالي 3–4 ريال للحصة — من أرخص الغداءات الكاملة.",
        },
        "nutritionFull": {
            "calories": "365",
            "protein": "12 g",
            "carbs": "58 g",
            "fat": "10 g",
            "fiber": "11 g",
            "sodium": "320 mg",
        },
        "ingredients": {
            "en": [
                "2 cups (320 g) cooked basmati rice, chilled",
                "1 can (400 g) chickpeas, drained and rinsed",
                "1 medium onion, thinly sliced",
                "2 medium tomatoes, diced (about 300 g)",
                "1 tsp ground turmeric",
                "1 tsp ground cumin",
                "2 tbsp (30 ml) vegetable or sunflower oil",
                "3 tbsp chopped fresh parsley",
                "Salt and black pepper to taste",
            ],
            "ar": [
                "كوبان (320 غ) أرز بسمتي مطبوخ بارد",
                "علبة (400 غ) حمص مصفى ومغسول",
                "بصلة متوسطة شرائح رفيعة",
                "حبتان طماطم مفرومتان (نحو 300 غ)",
                "ملعقة صغيرة كركم",
                "ملعقة صغيرة كمون",
                "ملعقتان كبيرتان زيت",
                "3 ملاعق كبيرة بقدونس مفروم",
                "ملح وفلفل أسود",
            ],
        },
        "steps": {
            "en": [
                "Heat oil in a wide pan over medium-high heat.",
                "Saute onion 5–6 minutes until golden at the edges.",
                "Add turmeric and cumin; stir 30 seconds until fragrant.",
                "Add tomatoes, salt, and pepper; cook 5 minutes until saucy.",
                "Stir in chickpeas; smash roughly one-third against the pan.",
                "Add rice; toss 4–5 minutes until heated through and evenly colored.",
                "Remove from heat; fold in parsley and adjust seasoning.",
                "Serve immediately with lemon if desired.",
            ],
            "ar": [
                "سخّني الزيت في مقلاة واسعة.",
                "البصل 5–6 دقائق حتى يذبل ويأخذ لون.",
                "كركم وكمون 30 ثانية.",
                "طماطم وملح 5 دقائق.",
                "حمص — اهرسي ثلث الكمية.",
                "أرز 4–5 دقائق حتى يسخن ويتلون.",
                "بقدونس بعد النار.",
                "قدّمي فوراً مع لمون.",
            ],
        },
    },
    "egg-tomato-skillet": {
        "story": {
            "en": [
                "Before the coffee finishes brewing, this skillet can be on the table — tomatoes breaking down in olive oil, cumin rising with the steam, eggs set under a lid just until the whites firm and the yolks stay soft if you like them that way. It mirrors shakshuka-adjacent comfort without needing a recipe book open.",
                "Gulf kitchens lean on eggs when meat prices spike or when Ramadan leftovers need a quick morning anchor. Serve with warm bread torn at the table; the sauce is built to be scooped, not politely forked. Scale chile heat down for children by setting their eggs aside before adding spice.",
            ],
            "ar": [
                "قبل ما يخلص القهوة، هالمقلاة ممكن تكون على الطاولة — طماطم تذوب بزيت الزيتون، كمون يطلع مع البخار، بيض يتماسك تحت الغطاء والصفار يبقى طري إذا تبغين. راحة قريبة من الشكشوكة بلا كتاب وصفات مفتوح.",
                "مطابخ الخليج تعتمد البيض لما أسعار اللحم تطلع أو بعد رمضان ويبغون فطور سريع. مع خبز دافئ ينقط بالصلصة — مو أكل مرتب بالشوكة. خفّفي الحرارة للعيال بفصل حصتهم قبل البهارات.",
            ],
        },
        "successTips": {
            "en": [
                "Use ripe tomatoes or add 1 tbsp tomato paste if winter tomatoes are pale — color drives flavor here.",
                "Cook tomatoes until the oil separates slightly at the edges before adding eggs.",
                "Cover the pan after adding eggs; steam sets whites without overcooking yolks on high heat.",
                "Crack eggs into small wells you make with the back of a spoon — even cooking.",
                "Finish with fresh cilantro or parsley off the heat so herbs stay green.",
            ],
            "ar": [
                "طماطم ناضجة — أو ملعقة معجون إذا الطماطم باهتة.",
                "اطبخي الطماطم لين الزيت يفصل شوي على الحواف قبل البيض.",
                "غطّي بعد البيض — البخار يثبت البياض بلا ما يمسك الصفار.",
                "اكسري البيض في حفر صغيرة بظهر الملعقة.",
                "كزبرة أو بقدونس بعد النار — يبقى أخضر.",
            ],
        },
        "variations": {
            "en": [
                "Add crumbled feta in the last minute for a sharper finish.",
                "Stir in 1/2 tsp smoked paprika with the cumin for depth.",
                "Use 6 eggs and stretch with extra tomato for a larger Friday brunch.",
                "Serve over leftover rice instead of bread for a heartier plate.",
            ],
            "ar": [
                "جبنة فيتا مفتتة آخر دقيقة.",
                "نصف ملعقة فلفل حلو مدخّن مع الكمون.",
                "6 بيضات وطماطم زيادة — فطور جمعة أكبر.",
                "فوق أرز متبقي بدل الخبز — وجبة أثقل.",
            ],
        },
        "serving": {
            "en": "Bring the skillet to the table on a trivet or divide into shallow bowls. Tear warm khubz or pita alongside and encourage scooping the sauce. Offer lemon wedges and a small dish of olives if you have them — salt and acid balance the cumin.",
            "ar": "قدّمي المقلاة على الطاولة أو قسّمي في أطباق. خبز عربي دافئ للغمس. لمون وزيتون جانباً يوازن الكمون.",
        },
        "storage": {
            "en": "Refrigerate up to 2 days. Reheat gently in a covered pan with 1 tbsp water; eggs will firm further. Not ideal frozen — yolks turn chalky. Best eaten within 24 hours for texture.",
            "ar": "ثلاجة يومين. سخّني برفق بغطاء وقليل ماء. التجميد مو مناسب — الصفار ييبس. أفضل خلال 24 ساعة.",
        },
        "costNote": {
            "en": "About 2–3 SAR per serving (eggs, tomatoes, onion, oil). One of the lowest-cost protein breakfasts in Gulf home cooking.",
            "ar": "حوالي 2–3 ريال للحصة — من أرخص فطور البروتين في البيت.",
        },
        "nutritionFull": {
            "calories": "285",
            "protein": "18 g",
            "carbs": "14 g",
            "fat": "18 g",
            "fiber": "3 g",
            "sodium": "420 mg",
        },
        "ingredients": {
            "en": [
                "4 large eggs",
                "4 medium tomatoes (500 g), diced",
                "1 medium onion, diced",
                "2 cloves garlic, minced",
                "1 tsp ground cumin",
                "1/2 tsp sweet paprika",
                "2 tbsp (30 ml) olive oil",
                "Salt and black pepper to taste",
                "2 tbsp chopped fresh cilantro or parsley",
            ],
            "ar": [
                "4 بيضات كبيرة",
                "4 حبات طماطم (500 غ) مفرومة",
                "بصلة متوسطة مفرومة",
                "2 فصوص ثوم",
                "ملعقة صغيرة كمون",
                "نصف ملعقة صغيرة فلفل حلو",
                "ملعقتان كبيرتان زيت زيتون",
                "ملح وفلفل",
                "ملعقتان كبيرتان كزبرة أو بقدونس",
            ],
        },
        "steps": {
            "en": [
                "Warm olive oil in a wide skillet over medium heat.",
                "Add onion; cook 4 minutes until softened. Stir in garlic and cumin 30 seconds.",
                "Add tomatoes, paprika, salt, and pepper. Simmer 8–10 minutes until saucy.",
                "Make four small wells in the sauce with a spoon back.",
                "Crack one egg into each well. Cover and cook 4–6 minutes to desired yolk set.",
                "Remove from heat; scatter herbs.",
                "Serve immediately with warm bread.",
            ],
            "ar": [
                "زيت زيتون على نار متوسطة.",
                "بصل 4 دقائق؛ ثوم وكمون 30 ثانية.",
                "طماطم وفلفل حلو وملح 8–10 دقائق.",
                "اعملي 4 حفر في الصلصة.",
                "بيضة في كل حفرة؛ غطّي 4–6 دقائق.",
                "كزبرة بعد النار.",
                "قدّمي فوراً مع خبز.",
            ],
        },
    },
    "lentil-koshari-bowl": {
        "story": {
            "en": [
                "Koshari street carts sell volume — this home version keeps the layered spirit without deep frying onions in a vat of oil. Brown lentils, rice, and small pasta each cook in their own pot, then meet in a bowl with slow-caramelized onion and a sharp vinegar-tomato sauce that wakes up leftover grains.",
                "Gulf families adopt koshari logic for meal prep Sundays: cook the three bases, refrigerate, and assemble bowls across the week. The sauce is deliberately tangy so a rich meal still feels bright in air-conditioned dining rooms. Kids often want extra sauce on the side — keep a jar in the fridge for that.",
            ],
            "ar": [
                "كشري الشارع يبيع كمية — النسخة البيتية تحافظ على الطبقات بلا قلي البصل بزيت عميق. عدس بني وأرز ومعكرونة صغيرة كل واحد في قدر، بعدين يلتقون في طبق مع بصل مكرمل ببطء وصلصة خل وطماطم تفتح نكهة الحبوب.",
                "بيوت الخليج تتبنى منطق الكشري يوم الأحد: تطبخ القواعد الثلاث، تبرد، وتركّب أطباق الأسبوع. الصلصة حامضة عمداً عشان الوجبة الثقيلة تبقى منعشة في غرف التكييف. العيال غالباً يبون صلصة زيادة — احفظي شوية في الثلاجة.",
            ],
        },
        "successTips": {
            "en": [
                "Salt each component lightly while cooking — layering unsalted grains tastes flat even with sauce.",
                "Caramelize onion on low heat 25–30 minutes with minimal oil; patience beats high heat browning.",
                "Rinse cooked lentils under warm water to remove starch foam before layering.",
                "Mix sauce just before serving so vinegar stays sharp; it dulls if held hot for hours.",
                "Use a wide shallow bowl — surface area lets sauce reach every grain.",
            ],
            "ar": [
                "ملّحي كل مكوّن شوي وقت الطبخ — طبقات بلا ملح تطلع باهتة حتى مع الصلصة.",
                "البصل على نار هادئة 25–30 دقيقة بزيت قليل — الصبر أحسن من التسرع.",
                "اغسلي العدس المطبوخ بماء دافئ عشان تروح الرغوة.",
                "اخلطي الصلصة قبل التقديم — الخل يبهت إذا حُمّي ساعات.",
                "طبق واسع وضحل — الصلصة توصل لكل حبة.",
            ],
        },
        "variations": {
            "en": [
                "Add 1 cup drained canned chickpeas to the lentil layer for extra protein.",
                "Use white vinegar or lime juice depending on what is in the pantry.",
                "Swap small macaroni for broken vermicelli toasted in dry pan before boiling.",
                "Top with fresh chopped parsley instead of fried onion for a lighter finish.",
            ],
            "ar": [
                "كوب حمص معلب مع طبقة العدس — بروتين زيادة.",
                "خل أبيض أو عصير ليمون — على حسب المخزن.",
                "شعيرية مكسورة محمّصة جافة بدل المكرونة.",
                "بقدونس طازج بدل البصل المقلي — أخف.",
            ],
        },
        "serving": {
            "en": "Spoon rice, then lentils, then pasta into each bowl without strict symmetry — home koshari is generous, not architectural. Ladle sauce over the top and add caramelized onion last so it stays visible. Serve with extra sauce and lemon wedges at the table for teenagers who always want more acid.",
            "ar": "أرز ثم عدس ثم معكرونة — مو لازم ترتيب فني. صلصة فوق وبصل مكرمل آخر شي. صلصة ولمون إضافي على الطاولة للي يحب الحموضة.",
        },
        "storage": {
            "en": "Store grains separately up to 4 days refrigerated. Sauce keeps 5 days; onion up to 3 days. Assemble bowls fresh — combined leftovers thicken and lose texture. Sauce can freeze 1 month; thaw and whisk before using.",
            "ar": "احفظي الحبوب منفصلة 4 أيام. الصلصة 5 أيام؛ البصل 3. ركّبي الطبق وقت الأكل — المخلوط يثخن. الصلصة تتجمّد شهر.",
        },
        "costNote": {
            "en": "About 4–6 SAR per serving (lentils, rice, pasta, onion, vinegar). One of the highest-volume budget dinners per riyal spent.",
            "ar": "حوالي 4–6 ريال للحصة — من أكثر العشاءات شبعاً بأقل تكلفة.",
        },
        "nutritionFull": {
            "calories": "405",
            "protein": "16 g",
            "carbs": "72 g",
            "fat": "6 g",
            "fiber": "10 g",
            "sodium": "480 mg",
        },
        "ingredients": {
            "en": [
                "1 cup (200 g) brown lentils, rinsed",
                "1 cup (190 g) long-grain rice, rinsed",
                "2 cups (200 g) small pasta (ditalini or macaroni)",
                "2 large onions: 1 sliced for caramelizing, 1 diced raw for garnish",
                "3 tbsp (45 ml) white vinegar",
                "2 tbsp (32 g) tomato paste",
                "1 tsp ground cumin",
                "2 tbsp (30 ml) sunflower oil",
                "1 tsp fine salt, plus more to taste",
            ],
            "ar": [
                "كوب (200 غ) عدس بني مغسول",
                "كوب (190 غ) أرز بسمتي مغسول",
                "كوبان (200 غ) معكرونة صغيرة",
                "بصلتان كبيرتان: واحدة شرائح للتكرمل وواحدة مفرومة للتزيين",
                "3 ملاعق كبيرة خل أبيض",
                "ملعقتان كبيرتان معجون طماطم",
                "ملعقة صغيرة كمون",
                "ملعقتان كبيرتان زيت",
                "ملعقة صغيرة ملح",
            ],
        },
        "steps": {
            "en": [
                "Cook lentils in 3 cups water 25–30 minutes until tender; drain and season lightly.",
                "Cook rice in 2 cups water per package; fluff and season lightly.",
                "Boil pasta in salted water until al dente; drain and toss with 1 tsp oil.",
                "Caramelize sliced onion in oil over low heat 25–30 minutes until deep gold.",
                "Whisk vinegar, tomato paste, cumin, salt, and 2 tbsp water for sauce.",
                "Layer rice, lentils, and pasta in bowls.",
                "Spoon sauce over; top with caramelized and raw onion.",
                "Serve immediately with extra sauce on the side.",
            ],
            "ar": [
                "عدس في 3 أكواب ماء 25–30 دقيقة؛ صفّيه وملّحي.",
                "أرز حسب التعليمات؛ فتّتيه وملّحي.",
                "معكرونة متماسكة؛ صفّيها وقلّبيها بملعقة زيت.",
                "بصل شرائح على نار هادئة 25–30 دقيقة حتى يتكرمل.",
                "اخلطي خل ومعجون وكمون وملح وملعقتين ماء.",
                "رتّبي أرز وعدس ومعكرونة.",
                "صلصة فوق؛ بصل مكرمل وني.",
                "قدّمي فوراً مع صلصة جانبية.",
            ],
        },
    },
    "veg-pasta-budget": {
        "story": {
            "en": [
                "When pasta is on sale and the crisper drawer has one zucchini and a lonely bell pepper, this skillet sauce is how Gulf home cooks stretch vegetables into a full dinner without a shopping trip. Tomato paste deepens flavor cheaply; a splash of pasta water emulsifies the sauce so it clings instead of pooling.",
                "It is deliberately mild — black pepper and garlic carry the dish, not chili — so toddlers and grandparents can share one pot. Grating cheese is optional; many families finish with olive oil and a squeeze of lemon when cheese prices climb.",
            ],
            "ar": [
                "لما المعكرونة عليها عرض والثلاجة فيها كوسا وفلفل وحيد، هالصلصة طريقة البيت الخليجي يمدّ فيها الخضار عشاء كامل بلا طلعة سوق. معجون الطماطم يعطي عمق بسعر بخس، وماء المعكرونة يخلي الصلصة تلزق مو تجمع.",
                "خفيفة عمداً — ثوم وفلفل أسود مو حار — عشان الصغار والكبار ياكلون من قدر واحد. الجبن اختياري؛ كثير ينهون بزيت زيتون ولمونة لما الجبن غالي.",
            ],
        },
        "successTips": {
            "en": [
                "Salt pasta water well — it is the only chance to season the noodles inside.",
                "Reserve 1 cup pasta water before draining; add gradually to loosen sauce.",
                "Cut vegetables similar size so they soften in the same 8-minute window.",
                "Cook tomato paste in oil 1 minute before adding wet ingredients — removes tinny taste.",
                "Toss pasta off the heat with sauce and 2 tbsp olive oil for a glossy finish.",
            ],
            "ar": [
                "ملّحي ماء المعكرونة زين — فرصة واحدة لتمليحها من الداخل.",
                "احتفظي بكوب ماء المعكرونة؛ أضيفيه تدريجياً.",
                "قطّعي الخضار بنفس الحجم — 8 دقائق تكفي للكل.",
                "حمّري معجون الطماطم بالزيت دقيقة قبل السائل.",
                "قلّبي المعكرونة بعد النار مع صلصة وملعقتين زيت — لمعان.",
            ],
        },
        "variations": {
            "en": [
                "Add 1 can drained chickpeas for protein when serving without meat.",
                "Stir in 1 tsp dried oregano or basil from the spice drawer.",
                "Use whole-wheat pasta for more fiber — add extra splash of water.",
                "Top adult portions with chili flakes at the table, not in the pot.",
            ],
            "ar": [
                "علبة حمص للبروتين إذا العشاء بلا لحم.",
                "ملعقة أوريجانو أو ريحان مجفف.",
                "معكرونة قمح كامل — ماء زيادة.",
                "شطة على الطاولة للكبار مو في القدر.",
            ],
        },
        "serving": {
            "en": "Twirl pasta into wide bowls so sauce sits on top, not sunk to the bottom. Offer grated cheese, olive oil, and black pepper at the table for self-service. A simple cucumber-yogurt side cools the palate in warm Gulf evenings.",
            "ar": "لفّي المعكرونة في أطباق واسعة. جبن وزيت زيتون وفلفل على الطاولة. سلطة خيار ولبن جانباً.",
        },
        "storage": {
            "en": "Refrigerate up to 3 days. Reheat in a pan with 2–3 tbsp water or pasta water, tossing until glossy. Sauce absorbs overnight — expect to add liquid. Not ideal frozen.",
            "ar": "ثلاجة 3 أيام. سخّني بمقلاة و2–3 ملاعق ماء. الصلصة تشرب ليلاً — زيدي سائل. التجميد مو أنسب.",
        },
        "costNote": {
            "en": "About 3–5 SAR per serving (pasta, tomato paste, seasonal vegetables). Cost drops when pasta and canned tomatoes are on promotion.",
            "ar": "حوالي 3–5 ريال للحصة. ينزل السعر مع عروض المعكرونة والطماطم.",
        },
        "nutritionFull": {
            "calories": "355",
            "protein": "11 g",
            "carbs": "62 g",
            "fat": "8 g",
            "fiber": "7 g",
            "sodium": "390 mg",
        },
        "ingredients": {
            "en": [
                "400 g dry pasta (penne or fusilli)",
                "1 medium zucchini (250 g), diced",
                "1 medium bell pepper (150 g), diced",
                "1 medium onion, diced",
                "3 cloves garlic, minced",
                "2 tbsp (32 g) tomato paste",
                "2 tbsp (30 ml) olive oil",
                "1 tsp fine salt, plus pasta water salt",
                "1/2 tsp black pepper",
            ],
            "ar": [
                "400 غ معكرونة قصيرة (أنبوبية أو حلزونية)",
                "كوسا متوسطة (250 غ) مكعبات",
                "فلفل رومي (150 غ) مكعبات",
                "بصلة متوسطة مفرومة",
                "3 فصوص ثوم",
                "ملعقتان كبيرتان معجون طماطم",
                "ملعقتان كبيرتان زيت زيتون",
                "ملعقة صغيرة ملح",
                "نصف ملعقة فلفل أسود",
            ],
        },
        "steps": {
            "en": [
                "Boil pasta in well-salted water until al dente; reserve 1 cup water, then drain.",
                "Warm olive oil in a large pan. Saute onion and pepper 5 minutes.",
                "Add zucchini and garlic; cook 4 minutes until edges soften.",
                "Stir tomato paste into the pan; cook 1 minute.",
                "Add 1/2 cup pasta water; simmer 3 minutes until lightly thickened.",
                "Toss drained pasta with sauce off the heat.",
                "Loosen with more pasta water if needed; season with pepper.",
                "Serve immediately with optional cheese or olive oil drizzle.",
            ],
            "ar": [
                "اسلقي المعكرونة متماسكة؛ احتفظي بكوب ماء وصفّي.",
                "زيت زيتون؛ بصل وفلفل 5 دقائق.",
                "كوسا وثوم 4 دقائق.",
                "معجون طماطم دقيقة.",
                "نصف كوب ماء معكرونة 3 دقائق.",
                "اخلطي المعكرونة بعد النار.",
                "ماء إضافي إذا لزم؛ فلفل.",
                "قدّمي فوراً.",
            ],
        },
    },
    "avocado-egg-toast": {
        "story": {
            "en": [
                "Avocado toast crossed from cafe menus into Gulf apartment kitchens because it solves the 10-minute breakfast problem with real fat and protein — not just carbs. Mash ripe avocado with lemon while bread toasts; a runny egg on top turns it into something that holds you until a late lunch meeting.",
                "Choose bread thick enough to support the weight — thin sliced sandwich loaf goes soggy under warm avocado. Gulf households often keep chili flakes off the shared plate and let adults add heat at the table. It is a weekday anchor, not a weekend project.",
            ],
            "ar": [
                "توست الأفوكادو دخل مطابخ شقق الخليج لأنه يحل فطور العشر دقائق بدهون وبروتين حقيقي — مو نشويات بس. هرّسي أفوكادو ناضج بلمون والخبز يتحمّص؛ بيضة طري فوق تحوله وجبة تمسكك لين غداء متأخر.",
                "اختاري خبز سميك يتحمل الوزن — شرائح رفيعة تطرّي تحت الأفوكادو الدافئ. البيوت تترك الشطة للكبار على الطاولة. فطور أيام الأسبوع مو مشروع نهاية الأسبوع.",
            ],
        },
        "successTips": {
            "en": [
                "Use avocado that yields slightly to pressure — hard fruit will not mash smoothly.",
                "Toast bread until crisp; moisture from avocado needs a sturdy base.",
                "Fry egg in a nonstick pan on medium — high heat toughens whites before yolk sets.",
                "Mash avocado with fork, not blender — you want texture, not puree.",
                "Add lemon immediately after mashing to slow browning if plates are delayed.",
            ],
            "ar": [
                "أفوكادو يلين بالضغط الخفيف — القاسي ما يهرس ناعم.",
                "حمّصي الخبز لين يقرمش — رطوبة الأفوكادو تحتاج قاعدة قوية.",
                "بيض على نار متوسطة — النار العالية تمسك البياض قبل الصفار.",
                "هرّسي بالشوكة مو الخلاط — تبغين قوام مو هريس.",
                "لمون فور الهرس يبطّئ اسمرار اللون.",
            ],
        },
        "variations": {
            "en": [
                "Swap fried egg for soft-boiled 6-minute egg sliced on top.",
                "Add 1 tbsp crumbled feta for saltiness without extra shaker salt.",
                "Use whole-grain bread for more fiber — toast longer for crunch.",
                "Top with everything bagel seasoning if you keep it in the pantry.",
            ],
            "ar": [
                "بيض مسلوق 6 دقائق مقطّع بدل المقلي.",
                "ملعقة فيتا مفتتة — ملح بلا زيادة.",
                "خبز قمح كامل — تحميص أطول.",
                "بهارات خبز إذا عندك.",
            ],
        },
        "serving": {
            "en": "Plate toast flat, not stacked — stacking steams the bottom slice. Cut in half on the diagonal for easier handling. Serve immediately while egg yolk is still runny if that is your preference. Coffee or karak alongside is the usual Gulf morning pairing.",
            "ar": "قدّمي التوست مسطّح مو مكدّس. قطّعي قطري للأكل الأسهل. فوراً والصفار طري. قهوة أو كرك بجانبها.",
        },
        "storage": {
            "en": "Not a make-ahead dish — avocado browns within 30 minutes. Assemble just before eating. Hard-boiled eggs can be prepped ahead; mash avocado fresh.",
            "ar": "مو للتحضير المسبق — الأفوكادو ياسمر خلال نصف ساعة. ركّبي وقت الأكل.",
        },
        "costNote": {
            "en": "About 5–8 SAR per serving (avocado, eggs, bread). Avocado price swings most; buy firm and ripen on the counter.",
            "ar": "حوالي 5–8 ريال للحصة — الأفوكادو هو المتغيّر. اشريه قاسي وخلّيه ينضج.",
        },
        "nutritionFull": {
            "calories": "340",
            "protein": "14 g",
            "carbs": "28 g",
            "fat": "20 g",
            "fiber": "8 g",
            "sodium": "310 mg",
        },
        "ingredients": {
            "en": [
                "2 slices thick whole-grain or sourdough bread",
                "1 ripe avocado (about 150 g)",
                "2 large eggs",
                "1 tsp lemon juice",
                "1/2 tsp fine salt",
                "1/4 tsp black pepper",
                "1 tsp olive oil or butter for frying",
            ],
            "ar": [
                "شريحتا خبز سميك (قمح كامل أو مخمّر)",
                "حبة أفوكادو ناضجة (150 غ)",
                "بيضتان كبيرتان",
                "ملعقة صغيرة عصير ليمون",
                "نصف ملعقة ملح",
                "ربع ملعقة فلفل أسود",
                "ملعقة زيت زيتون أو زبدة للقلي",
            ],
        },
        "steps": {
            "en": [
                "Toast bread until golden and crisp.",
                "Halve avocado; scoop flesh into a bowl with lemon, salt, and pepper. Mash with a fork.",
                "Heat oil in a nonstick pan over medium heat.",
                "Crack eggs; fry 2–3 minutes until whites set and yolks still runny.",
                "Spread avocado generously on each toast slice.",
                "Top each slice with one fried egg.",
                "Season with extra pepper. Serve immediately.",
            ],
            "ar": [
                "حمّصي الخبز حتى يقرمش.",
                "افتحي الأفوكادو؛ هرّسي اللحم مع ليمون وملح وفلفل.",
                "زيت في مقلاة على نار متوسطة.",
                "بيض 2–3 دقائق — بياض متماسك وصفار طري.",
                "افردي الأفوكادو على الخبز.",
                "بيضة فوق كل شريحة.",
                "فلفل وقدّمي فوراً.",
            ],
        },
    },
    "tuna-wrap-quick": {
        "story": {
            "en": [
                "Five minutes from pantry to hand — that is the contract this wrap keeps when school pickup runs late or someone needs lunch before a dentist appointment. Canned tuna, yogurt instead of heavy mayo, and crunchy cucumber inside a warmed tortilla feels like a proper meal, not a sad desk sandwich.",
                "Gulf families stock oil-packed and water-packed tuna depending on taste; water-packed keeps the wrap from leaking in a lunch bag. Warm the tortilla 20 seconds so it bends without tearing — cold stiff bread shatters when rolled tight.",
            ],
            "ar": [
                "خمس دقائق من المخزن لليد — هالعقد اللي تلتزم فيه اللفافة لما الاستلام من المدرسة يتأخر أو أحد يبي غداء قبل الموعد. تونة معلبة، لبن بدل مايونيز ثقيل، وخيار مقرمش داخل لفافة دافئة — وجبة حقيقية مو ساندويتش حزين.",
                "بيوت الخليج تخزّن تونة بالزيت أو بالماء — بالماء أقل تسريب في شنطة الغداء. سخّني اللفافة 20 ثانية عشان تنحني بلا ما تنكسر.",
            ],
        },
        "successTips": {
            "en": [
                "Drain tuna thoroughly; wet filling makes wraps soggy within minutes.",
                "Mix filling before assembling so yogurt coats every flake evenly.",
                "Lay filling in a horizontal band across the lower third — not centered blob.",
                "Fold sides in, then roll tight from bottom; seam down on the plate.",
                "If packing for travel, wrap in foil and keep chilled until eating.",
            ],
            "ar": [
                "صفّي التونة زين — الرطوبة تطرّي اللفافة.",
                "اخلطي الحشوة قبل اللف — اللبن يغطي كل قطعة.",
                "الحشوة شريط أفقي في الثلث السفلي.",
                "طوّي الجوانب ولفّي من تحت؛ اللحام تحت.",
                "للتنقل: ورق قصدير وبرّد لين وقت الأكل.",
            ],
        },
        "variations": {
            "en": [
                "Add 1 tbsp capers or chopped pickles for Gulf-style tang.",
                "Use large khubz or lavash instead of flour tortilla.",
                "Stir in 1 tsp harissa for adults; pack plain for kids.",
                "Swap yogurt for labneh thinned with 1 tbsp water.",
            ],
            "ar": [
                "كبر أو مخلل مفروم — حموضة على طريقة الخليج.",
                "خبز عربي كبير أو خبز رقيق بدل لفافة الدقيق.",
                "هريسة للكبار؛ سادة للعيال.",
                "لبنة مخفّفة بملعقة ماء بدل اللبن.",
            ],
        },
        "serving": {
            "en": "Cut diagonally if serving on a plate so filling shows; eat whole if walking. Pair with apple slices or carrot sticks for crunch. Serve within 30 minutes of assembly for best texture.",
            "ar": "قطّعي قطري على الطبق؛ كاملة لو تمشين. تفاح أو جزر جانباً. خلال 30 دقيقة من التحضير.",
        },
        "storage": {
            "en": "Best eaten fresh. Refrigerate wrapped up to 4 hours; tortilla softens over time. Do not freeze — cucumber turns watery on thaw.",
            "ar": "أفضلها طازجة. ثلاجة 4 ساعات؛ اللفافة تلين. لا تجمّدي — الخيار يطرّي.",
        },
        "costNote": {
            "en": "About 4–6 SAR per wrap (canned tuna, tortilla, yogurt, vegetables). Stock tuna on promotion for closer to 3 SAR.",
            "ar": "حوالي 4–6 ريال للفافة. عروض التونة تنزلها نحو 3 ريال.",
        },
        "nutritionFull": {
            "calories": "295",
            "protein": "24 g",
            "carbs": "28 g",
            "fat": "10 g",
            "fiber": "4 g",
            "sodium": "520 mg",
        },
        "ingredients": {
            "en": [
                "2 cans (280 g drained) tuna in water, drained well",
                "4 large flour tortillas (about 60 cm)",
                "1/2 cup (120 g) plain yogurt",
                "1 medium cucumber (150 g), diced",
                "2 tbsp (30 g) chopped pickles",
                "1 tbsp (15 ml) lemon juice",
                "1/4 tsp black pepper",
                "4 lettuce leaves (optional)",
            ],
            "ar": [
                "علبتان (280 غ مصفى) تونة بالماء",
                "4 لفائف دقيق كبيرة",
                "نصف كوب (120 غ) لبن طبيعي",
                "خيار متوسط (150 غ) مكعبات",
                "ملعقتان كبيرتان مخلل مفروم",
                "ملعقة كبيرة عصير ليمون",
                "ربع ملعقة فلفل أسود",
                "4 أوراق خس (اختياري)",
            ],
        },
        "steps": {
            "en": [
                "Drain tuna; flake into a bowl.",
                "Mix yogurt, lemon, pepper, cucumber, and pickles into tuna.",
                "Warm each tortilla 20 seconds in a dry pan or microwave.",
                "Lay one lettuce leaf on tortilla if using.",
                "Spread one-quarter of filling in a band on lower third.",
                "Fold sides in; roll tightly from bottom.",
                "Repeat for remaining wraps. Serve seam-side down.",
            ],
            "ar": [
                "صفّي التونة وفتّتها.",
                "اخلطي لبن ولمون وفلفل وخيار ومخلل.",
                "سخّني كل لفافة 20 ثانية.",
                "خس إذا تبغين.",
                "ربع الحشوة في الثلث السفلي.",
                "طوّي الجوانب ولفّي.",
                "كرّري. قدّمي اللحام تحت.",
            ],
        },
    },
}
