#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Ensure site header includes hamburger + mobile-dropdown on all pages."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PARTIALS = ROOT / "partials"

SKIP_DIRS = {"outputs", "legacy", ".git", "node_modules", "__pycache__", "partials"}

HEADER_START = "<!-- ═══ UNIFIED HEADER"
HEADER_END = "<!-- ═══ END HEADER"

UNIFIED_BLOCK = re.compile(
    r"<!-- ═══ UNIFIED HEADER[^>]*═+\s*-->.*?<!-- ═══ END HEADER[^>]*═+\s*-->",
    re.I | re.S,
)

NAV_BLOCK = re.compile(r'<nav id="navbar"[^>]*>.*?</nav>', re.I | re.S)


def load_chrome() -> str:
    header = (PARTIALS / "header.html").read_text(encoding="utf-8").strip()
    dropdown = (PARTIALS / "mobile-dropdown.html").read_text(encoding="utf-8").strip()
    return (
        f"{HEADER_START} ══════════════════════════════════════ -->\n"
        f"{header}\n"
        f"{dropdown}\n"
        f"{HEADER_END} ══════════════════════════════════════ -->"
    )


def should_skip(path: Path) -> bool:
    if any(part in SKIP_DIRS for part in path.parts):
        return True
    # Recipe pages are generated by build_recipe_* — avoid double chrome injection
    return path.parts[:2] == ("library", "recipes") if len(path.parts) >= 2 else False


def inject_dropdown_after_nav(text: str, dropdown: str) -> tuple[str, bool]:
    """Insert mobile dropdown immediately after navbar when hamburger exists."""
    if "mobile-dropdown" in text:
        return text, False
    if "hamburger-btn" not in text:
        return text, False

    m = NAV_BLOCK.search(text)
    if not m:
        return text, False

    insert_at = m.end()
    return text[:insert_at] + "\n" + dropdown + text[insert_at:], True


def patch_file(text: str, chrome: str, dropdown_only: str) -> tuple[str, str]:
    if UNIFIED_BLOCK.search(text):
        new_text = UNIFIED_BLOCK.sub(chrome, text, count=1)
        if new_text != text:
            return new_text, "unified"
        return text, "skip"

    if "hamburger-btn" not in text and NAV_BLOCK.search(text):
        is_article = (
            'data-template="article"' in text
            or 'class="article-wrap"' in text
            or "/scripts/global.js" in text
        )
        has_unified_markers = HEADER_START in text
        if is_article and not has_unified_markers:
            header = (PARTIALS / "header.html").read_text(encoding="utf-8").strip()
            replacement = (
                f"{HEADER_START} ══════════════════════════════════════ -->\n"
                f"{header}\n{dropdown_only}\n"
                f"{HEADER_END} ══════════════════════════════════════ -->"
            )
            new_text = NAV_BLOCK.sub(replacement, text, count=1)
            if new_text != text:
                return new_text, "nav"

    new_text, changed = inject_dropdown_after_nav(text, dropdown_only)
    if changed:
        return new_text, "inject"

    return text, "skip"


def dedupe_mobile_dropdown(text: str) -> tuple[str, bool]:
    """Keep only the first mobile-dropdown block."""
    pattern = re.compile(
        r"<!-- ── Mobile dropdown menu ── -->\s*"
        r'<div class="mobile-dropdown" id="mobile-dropdown"[^>]*>.*?</div>',
        re.I | re.S,
    )
    matches = list(pattern.finditer(text))
    if len(matches) <= 1:
        return text, False
    # Remove duplicates from last to first
    new_text = text
    for m in reversed(matches[1:]):
        new_text = new_text[: m.start()] + new_text[m.end() :]
    # Collapse duplicate header marker lines
    new_text = re.sub(
        rf"({re.escape(HEADER_START)}[^\\n]*\\n)\\s*\\1",
        r"\1",
        new_text,
    )
    new_text = re.sub(
        rf"({re.escape(HEADER_END)}[^\\n]*\\n)\\s*\\1",
        r"\1",
        new_text,
    )
    return new_text, True


def main() -> None:
    chrome = load_chrome()
    dropdown_only = (PARTIALS / "mobile-dropdown.html").read_text(encoding="utf-8").strip()
    stats = {"unified": 0, "nav": 0, "inject": 0, "dedupe": 0, "skip": 0}

    for path in sorted(ROOT.rglob("*.html")):
        if should_skip(path):
            continue
        original = path.read_text(encoding="utf-8")
        updated, action = patch_file(original, chrome, dropdown_only)
        deduped, was_deduped = dedupe_mobile_dropdown(updated)
        if was_deduped:
            action = "dedupe" if action == "skip" else action
            updated = deduped
        stats[action] = stats.get(action, 0) + 1
        if updated != original:
            path.write_text(updated, encoding="utf-8")
            print(f"  {action:7} {path.relative_to(ROOT)}")

    print(
        f"\nDone: unified={stats.get('unified', 0)} "
        f"nav={stats.get('nav', 0)} "
        f"inject={stats.get('inject', 0)} "
        f"dedupe={stats.get('dedupe', 0)} skip={stats.get('skip', 0)}"
    )


if __name__ == "__main__":
    main()
